//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.15 at 06:00:56 PM BST 
//


package org.gosh.re.dmcash.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GiftSubtype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GiftSubtype">
 *   &lt;restriction base="{}String50">
 *     &lt;enumeration value="Donations - 1010"/>
 *     &lt;enumeration value="Donations - Company - 1011"/>
 *     &lt;enumeration value="Donations - Company Customer - 1012"/>
 *     &lt;enumeration value="Donations - Justgiving - 1013"/>
 *     &lt;enumeration value="Donations - Internet - 1014"/>
 *     &lt;enumeration value="Donations - Shares - 1015"/>
 *     &lt;enumeration value="Pin Badges - 1020"/>
 *     &lt;enumeration value="Collections - Public - 1025"/>
 *     &lt;enumeration value="Collections - Static - 1026"/>
 *     &lt;enumeration value="Payroll Giving - 1030"/>
 *     &lt;enumeration value="Employee Fundraising - 1035"/>
 *     &lt;enumeration value="Sponsorship - 1040"/>
 *     &lt;enumeration value="Ticket Sales - 1045"/>
 *     &lt;enumeration value="Gifts in Kind - 1050"/>
 *     &lt;enumeration value="Raffle - 1055"/>
 *     &lt;enumeration value="Event - Other - 1060"/>
 *     &lt;enumeration value="Sales - Standard Rated - 1070"/>
 *     &lt;enumeration value="Sales -  Zero Rated - 1071"/>
 *     &lt;enumeration value="Sales - Exempt - 1072"/>
 *     &lt;enumeration value="Sales - Outside scope of vat - 1073"/>
 *     &lt;enumeration value="Royalties - Vatable - 1074"/>
 *     &lt;enumeration value="Royalties - NonVatable - 1075"/>
 *     &lt;enumeration value="Membership - 1200"/>
 *     &lt;enumeration value="Auction Fee - 1300"/>
 *     &lt;enumeration value="Virtual Product - 1305"/>
 *     &lt;enumeration value="Sale of Donated Goods - 1310"/>
 *     &lt;enumeration value="Other Misc. Income - 1802"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GiftSubtype")
@XmlEnum
public enum GiftSubtype {

    @XmlEnumValue("Donations - 1010")
    DONATIONS_1010("Donations - 1010"),
    @XmlEnumValue("Donations - Company - 1011")
    DONATIONS_COMPANY_1011("Donations - Company - 1011"),
    @XmlEnumValue("Donations - Company Customer - 1012")
    DONATIONS_COMPANY_CUSTOMER_1012("Donations - Company Customer - 1012"),
    @XmlEnumValue("Donations - Justgiving - 1013")
    DONATIONS_JUSTGIVING_1013("Donations - Justgiving - 1013"),
    @XmlEnumValue("Donations - Internet - 1014")
    DONATIONS_INTERNET_1014("Donations - Internet - 1014"),
    @XmlEnumValue("Donations - Shares - 1015")
    DONATIONS_SHARES_1015("Donations - Shares - 1015"),
    @XmlEnumValue("Pin Badges - 1020")
    PIN_BADGES_1020("Pin Badges - 1020"),
    @XmlEnumValue("Collections - Public - 1025")
    COLLECTIONS_PUBLIC_1025("Collections - Public - 1025"),
    @XmlEnumValue("Collections - Static - 1026")
    COLLECTIONS_STATIC_1026("Collections - Static - 1026"),
    @XmlEnumValue("Payroll Giving - 1030")
    PAYROLL_GIVING_1030("Payroll Giving - 1030"),
    @XmlEnumValue("Employee Fundraising - 1035")
    EMPLOYEE_FUNDRAISING_1035("Employee Fundraising - 1035"),
    @XmlEnumValue("Sponsorship - 1040")
    SPONSORSHIP_1040("Sponsorship - 1040"),
    @XmlEnumValue("Ticket Sales - 1045")
    TICKET_SALES_1045("Ticket Sales - 1045"),
    @XmlEnumValue("Gifts in Kind - 1050")
    GIFTS_IN_KIND_1050("Gifts in Kind - 1050"),
    @XmlEnumValue("Raffle - 1055")
    RAFFLE_1055("Raffle - 1055"),
    @XmlEnumValue("Event - Other - 1060")
    EVENT_OTHER_1060("Event - Other - 1060"),
    @XmlEnumValue("Sales - Standard Rated - 1070")
    SALES_STANDARD_RATED_1070("Sales - Standard Rated - 1070"),
    @XmlEnumValue("Sales -  Zero Rated - 1071")
    SALES_ZERO_RATED_1071("Sales -  Zero Rated - 1071"),
    @XmlEnumValue("Sales - Exempt - 1072")
    SALES_EXEMPT_1072("Sales - Exempt - 1072"),
    @XmlEnumValue("Sales - Outside scope of vat - 1073")
    SALES_OUTSIDE_SCOPE_OF_VAT_1073("Sales - Outside scope of vat - 1073"),
    @XmlEnumValue("Royalties - Vatable - 1074")
    ROYALTIES_VATABLE_1074("Royalties - Vatable - 1074"),
    @XmlEnumValue("Royalties - NonVatable - 1075")
    ROYALTIES_NON_VATABLE_1075("Royalties - NonVatable - 1075"),
    @XmlEnumValue("Membership - 1200")
    MEMBERSHIP_1200("Membership - 1200"),
    @XmlEnumValue("Auction Fee - 1300")
    AUCTION_FEE_1300("Auction Fee - 1300"),
    @XmlEnumValue("Virtual Product - 1305")
    VIRTUAL_PRODUCT_1305("Virtual Product - 1305"),
    @XmlEnumValue("Sale of Donated Goods - 1310")
    SALE_OF_DONATED_GOODS_1310("Sale of Donated Goods - 1310"),
    @XmlEnumValue("Other Misc. Income - 1802")
    OTHER_MISC_INCOME_1802("Other Misc. Income - 1802");
    private final String value;

    GiftSubtype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GiftSubtype fromValue(String v) {
        for (GiftSubtype c: GiftSubtype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
