//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.15 at 06:00:56 PM BST 
//


package org.gosh.re.dmcash.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gosh.re.dmcash.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gosh.re.dmcash.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GOSHCC.Relationship.Attributes }
     * 
     */
    public GOSHCC.Relationship.Attributes createGOSHCCRelationshipAttributes() {
        return new GOSHCC.Relationship.Attributes();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType }
     * 
     */
    public GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType createGOSHCCDonorCplxTypeDonationDetailsDirectDebitDonationCplxType() {
        return new GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes createGOSHCCDonorCplxTypeAttributes() {
        return new GOSHCC.DonorCplxType.Attributes();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes.DeceasedNotificationDate }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes.DeceasedNotificationDate createGOSHCCDonorCplxTypeAttributesDeceasedNotificationDate() {
        return new GOSHCC.DonorCplxType.Attributes.DeceasedNotificationDate();
    }

    /**
     * Create an instance of {@link GOSHCC }
     * 
     */
    public GOSHCC createGOSHCC() {
        return new GOSHCC();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.DonationDetails }
     * 
     */
    public GOSHCC.DonorCplxType.DonationDetails createGOSHCCDonorCplxTypeDonationDetails() {
        return new GOSHCC.DonorCplxType.DonationDetails();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes.Source }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes.Source createGOSHCCDonorCplxTypeAttributesSource() {
        return new GOSHCC.DonorCplxType.Attributes.Source();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Action.Attributes }
     * 
     */
    public GOSHCC.DonorCplxType.Action.Attributes createGOSHCCDonorCplxTypeActionAttributes() {
        return new GOSHCC.DonorCplxType.Action.Attributes();
    }

    /**
     * Create an instance of {@link GOSHCC.Relationship }
     * 
     */
    public GOSHCC.Relationship createGOSHCCRelationship() {
        return new GOSHCC.Relationship();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes.DirectMarketingType }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes.DirectMarketingType createGOSHCCDonorCplxTypeAttributesDirectMarketingType() {
        return new GOSHCC.DonorCplxType.Attributes.DirectMarketingType();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.PhoneEmail }
     * 
     */
    public GOSHCC.DonorCplxType.PhoneEmail createGOSHCCDonorCplxTypePhoneEmail() {
        return new GOSHCC.DonorCplxType.PhoneEmail();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes.SchoolOrYouthType }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes.SchoolOrYouthType createGOSHCCDonorCplxTypeAttributesSchoolOrYouthType() {
        return new GOSHCC.DonorCplxType.Attributes.SchoolOrYouthType();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.PDDUpgradeFlag }
     * 
     */
    public GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.PDDUpgradeFlag createGOSHCCDonorCplxTypeDonationDetailsDirectDebitDonationCplxTypePDDUpgradeFlag() {
        return new GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.PDDUpgradeFlag();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Action }
     * 
     */
    public GOSHCC.DonorCplxType.Action createGOSHCCDonorCplxTypeAction() {
        return new GOSHCC.DonorCplxType.Action();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.ConsCodes }
     * 
     */
    public GOSHCC.DonorCplxType.ConsCodes createGOSHCCDonorCplxTypeConsCodes() {
        return new GOSHCC.DonorCplxType.ConsCodes();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.DonationDetails.CashDonationCplxType }
     * 
     */
    public GOSHCC.DonorCplxType.DonationDetails.CashDonationCplxType createGOSHCCDonorCplxTypeDonationDetailsCashDonationCplxType() {
        return new GOSHCC.DonorCplxType.DonationDetails.CashDonationCplxType();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.TaxDeclaration }
     * 
     */
    public GOSHCC.DonorCplxType.TaxDeclaration createGOSHCCDonorCplxTypeTaxDeclaration() {
        return new GOSHCC.DonorCplxType.TaxDeclaration();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.ConstituentAppeal }
     * 
     */
    public GOSHCC.DonorCplxType.ConstituentAppeal createGOSHCCDonorCplxTypeConstituentAppeal() {
        return new GOSHCC.DonorCplxType.ConstituentAppeal();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.NonConstituentOrganisationRelationship }
     * 
     */
    public GOSHCC.DonorCplxType.NonConstituentOrganisationRelationship createGOSHCCDonorCplxTypeNonConstituentOrganisationRelationship() {
        return new GOSHCC.DonorCplxType.NonConstituentOrganisationRelationship();
    }

    /**
     * Create an instance of {@link GOSHCC.Tribute }
     * 
     */
    public GOSHCC.Tribute createGOSHCCTribute() {
        return new GOSHCC.Tribute();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.DonorBankCplxType }
     * 
     */
    public GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.DonorBankCplxType createGOSHCCDonorCplxTypeDonationDetailsDirectDebitDonationCplxTypeDonorBankCplxType() {
        return new GOSHCC.DonorCplxType.DonationDetails.DirectDebitDonationCplxType.DonorBankCplxType();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType.Attributes.SolicitCodes }
     * 
     */
    public GOSHCC.DonorCplxType.Attributes.SolicitCodes createGOSHCCDonorCplxTypeAttributesSolicitCodes() {
        return new GOSHCC.DonorCplxType.Attributes.SolicitCodes();
    }

    /**
     * Create an instance of {@link GiftAttributes }
     * 
     */
    public GiftAttributes createGiftAttributes() {
        return new GiftAttributes();
    }

    /**
     * Create an instance of {@link GOSHCC.DonorCplxType }
     * 
     */
    public GOSHCC.DonorCplxType createGOSHCCDonorCplxType() {
        return new GOSHCC.DonorCplxType();
    }

}
