
package org.gosh.validation.general.accountnumber.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Jul 21 11:25:18 BST 2011
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber", name = "SvcGetAccountNumberSoap")
@XmlSeeAlso({ObjectFactory.class})

public interface SvcGetAccountNumberSoap {

    @WebResult(name = "GetAccountNumberResult", targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber")
    @RequestWrapper(localName = "GetAccountNumber", targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber", className = "org.gosh.webservices.getAccountNumber.GetAccountNumber")
    @ResponseWrapper(localName = "GetAccountNumberResponse", targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber", className = "org.gosh.webservices.getAccountNumber.GetAccountNumberResponse")
    @WebMethod(operationName = "GetAccountNumber", action = "http://tempuri.org/.NetWebService/WS-GetAccountNumber/GetAccountNumber")
    public org.gosh.validation.general.accountnumber.ws.Report getAccountNumber(
        @WebParam(name = "IBankId", targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber")
        int iBankId
    );
}
