
package org.gosh.validation.general.bank.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Jan 12 16:26:16 GMT 2010
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "SvcGetBankDetForPledge", targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", wsdlLocation = "http://goshcc-iis2test/services/getBankDetailsForPledge.asmx?WSDL")
public class SvcGetBankDetForPledge extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", "SvcGetBankDetForPledge");
    public final static QName SvcGetBankDetForPledgeSoap = new QName("http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", "SvcGetBankDetForPledgeSoap");
    public final static QName SvcGetBankDetForPledgeSoap12 = new QName("http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", "SvcGetBankDetForPledgeSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://goshcc-iis2test/services/getBankDetailsForPledge.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://goshcc-iis2test/services/getBankDetailsForPledge.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SvcGetBankDetForPledge(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcGetBankDetForPledge(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcGetBankDetForPledge() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SvcGetBankDetForPledgeSoap
     */
    @WebEndpoint(name = "SvcGetBankDetForPledgeSoap")
    public SvcGetBankDetForPledgeSoap getSvcGetBankDetForPledgeSoap() {
        return super.getPort(SvcGetBankDetForPledgeSoap, SvcGetBankDetForPledgeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcGetBankDetForPledgeSoap
     */
    @WebEndpoint(name = "SvcGetBankDetForPledgeSoap")
    public SvcGetBankDetForPledgeSoap getSvcGetBankDetForPledgeSoap(WebServiceFeature... features) {
        return super.getPort(SvcGetBankDetForPledgeSoap, SvcGetBankDetForPledgeSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns SvcGetBankDetForPledgeSoap
     */
    @WebEndpoint(name = "SvcGetBankDetForPledgeSoap12")
    public SvcGetBankDetForPledgeSoap getSvcGetBankDetForPledgeSoap12() {
        return super.getPort(SvcGetBankDetForPledgeSoap12, SvcGetBankDetForPledgeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcGetBankDetForPledgeSoap
     */
    @WebEndpoint(name = "SvcGetBankDetForPledgeSoap12")
    public SvcGetBankDetForPledgeSoap getSvcGetBankDetForPledgeSoap12(WebServiceFeature... features) {
        return super.getPort(SvcGetBankDetForPledgeSoap12, SvcGetBankDetForPledgeSoap.class, features);
    }

}
