
package org.gosh.validation.general.bank.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Jan 12 16:26:16 GMT 2010
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", name = "SvcGetBankDetForPledgeSoap")
@XmlSeeAlso({ObjectFactory.class})

public interface SvcGetBankDetForPledgeSoap {

    @WebResult(name = "GetBankDetailsResult", targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge")
    @RequestWrapper(localName = "GetBankDetails", targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", className = "org.gosh.webservices.getBankDetailsForPledge.GetBankDetails")
    @ResponseWrapper(localName = "GetBankDetailsResponse", targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge", className = "org.gosh.webservices.getBankDetailsForPledge.GetBankDetailsResponse")
    @WebMethod(operationName = "GetBankDetails", action = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge/GetBankDetails")
    public org.gosh.validation.general.bank.ws.BankReportTool getBankDetails(
        @WebParam(name = "giftImportID", targetNamespace = "http://goshcc.org/.NetServices/WS-GetBankDetailsForPledge")
        java.lang.String giftImportID
    );
}
