
package org.gosh.validation.general.accountnumber.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Jul 21 11:25:18 BST 2011
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "SvcGetAccountNumber", targetNamespace = "http://tempuri.org/.NetWebService/WS-GetAccountNumber", wsdlLocation = "http://goshcc-iis2test/services/getAccountNumber.asmx?WSDL")
public class SvcGetAccountNumber extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/.NetWebService/WS-GetAccountNumber", "SvcGetAccountNumber");
    public final static QName SvcGetAccountNumberSoap = new QName("http://tempuri.org/.NetWebService/WS-GetAccountNumber", "SvcGetAccountNumberSoap");
    public final static QName SvcGetAccountNumberSoap12 = new QName("http://tempuri.org/.NetWebService/WS-GetAccountNumber", "SvcGetAccountNumberSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://goshcc-iis2test/services/getAccountNumber.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://goshcc-iis2test/services/getAccountNumber.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SvcGetAccountNumber(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcGetAccountNumber(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcGetAccountNumber() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SvcGetAccountNumberSoap
     */
    @WebEndpoint(name = "SvcGetAccountNumberSoap")
    public SvcGetAccountNumberSoap getSvcGetAccountNumberSoap() {
        return super.getPort(SvcGetAccountNumberSoap, SvcGetAccountNumberSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcGetAccountNumberSoap
     */
    @WebEndpoint(name = "SvcGetAccountNumberSoap")
    public SvcGetAccountNumberSoap getSvcGetAccountNumberSoap(WebServiceFeature... features) {
        return super.getPort(SvcGetAccountNumberSoap, SvcGetAccountNumberSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns SvcGetAccountNumberSoap
     */
    @WebEndpoint(name = "SvcGetAccountNumberSoap12")
    public SvcGetAccountNumberSoap getSvcGetAccountNumberSoap12() {
        return super.getPort(SvcGetAccountNumberSoap12, SvcGetAccountNumberSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcGetAccountNumberSoap
     */
    @WebEndpoint(name = "SvcGetAccountNumberSoap12")
    public SvcGetAccountNumberSoap getSvcGetAccountNumberSoap12(WebServiceFeature... features) {
        return super.getPort(SvcGetAccountNumberSoap12, SvcGetAccountNumberSoap.class, features);
    }

}
