//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.01 at 12:16:18 PM BST 
//


package org.gosh.gfu.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gosh.gfu.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gosh.gfu.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Supporter.Packs.Pack }
     * 
     */
    public Supporter.Packs.Pack createSupporterPacksPack() {
        return new Supporter.Packs.Pack();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Supporter.Packs }
     * 
     */
    public Supporter.Packs createSupporterPacks() {
        return new Supporter.Packs();
    }

    /**
     * Create an instance of {@link Supporter }
     * 
     */
    public Supporter createSupporter() {
        return new Supporter();
    }

}
